# Wokwi Configuration File
# Reference: config
[wokwi]
version = 1
firmware = '.pio/build/esp32/firmware.bin'
elf = '.pio/build/esp32/firmware.elf'

[[chip]]
name='gps-neo6m'
binary='chips/mode-urbana/gps-neo6m.chip.wasm'