import glob
import pathlib


def convertSentence(sentence: str):
    return f'"{sentence.strip()}\\r\\n"'


for filepath in glob.glob("**/*.nmea", recursive=True):
    with open(filepath, encoding="utf-8") as fs:
        sentences = fs.readlines()

    path = pathlib.Path(filepath).with_suffix(".c")
    with path.open("w", encoding="utf-8") as fs:
        code = "  // autogenerated from " + filepath
        code += "\n  const char gps_tx_data[][80] = { // GPRMC & GPGGA (Hypothetical Data)\n    "
        code += ",\n    ".join(map(convertSentence, sentences))
        code += "\n  };"
        fs.write(code)
